# Generated by Django 5.0.6 on 2024-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                ("model_type", models.CharField(max_length=100)),
                ("max_speed", models.IntegerField()),
                ("max_height", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "icloud_login",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "icloud_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("coordinates", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
