# Generated by Django 5.0.6 on 2024-06-06 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uav", "0004_alter_uav_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="uav",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="uavs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
